apiVersion: v1
kind: Service
metadata:
  name: service-sql
  labels:
    app: sql
spec:
  ports:
  - port: 3306
    name: web
  clusterIP: None
  selector:
    app: sql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql
spec:
  serviceName: service-sql
  replicas: 2
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: nginx
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: web
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: menachem
        volumeMounts:
        - name: www
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

